### ISSUE TITLE
Sub-folders

### ISSUE THREAD

**Issue by AuracleTech** [Jose134/HDtoSD#2]
Hello, again thank you for the program I use and share it a lot!
Can you make it so it's able to do the same thing for sub-folders (_all_ folders present in skin folder, like score, combo etc...)?

**Comment by Jose134** [comment]
Done ;)
You can find the executable in [releases](https://github.com/Jose134/HDtoSD/releases)

I added a command line argument (-s [true/false]) to enable or disable searching files in subdirectories. If the argument isn't provided then the program will ask if you want this option before searching for files.
